from .ssvepformer import SSVEPformer,init_normal
from .fuzzy_ssvepformerT1 import fuzzySSVEPformerA,fuzzySSVEPformerB,fuzzySSVEPformerC
from .fuzzy_ssvepformerT2 import fuzzyT2SSVEPformerA,fuzzyT2SSVEPformerB,fuzzyT2SSVEPformerC
from .fbssvepformer import FBSSVEPformer